name: CI Pipeline

on:
  push:
    branches: [ "main", "fire" ]
  pull_request:
    branches: [ "main", "fire" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:   
    - name: Kodu Çek
      uses: actions/checkout@v3

    - name: Node.js Kurulumu
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Bağımlılıkları Yükle
      run: npm install

    - name: ESLint Kontrolü
      run: npm run lint

    - name: Testleri Çalıştır
      run: npm test